### PR TITLE
Replaced owl:Class with wol:Class

### LINKED ISSUE #616: Set up an "offline" Git repository
This is not a proper issue, but a good first task of setting up a clone of this repository on a local or remote computer, for everyone who wants to edit EDAM locally (or on a remote machine via _ssh_).

1. Fork this repository into your user space on GitHub _(read below if not sure how)_
2. Clone it onto your local machine
3. Set up your local repository, following the instructions in [CONTRIBUTING.md](https://github.com/edamontology/edamontology/blob/main/CONTRIBUTING.md#git-setup-on-your-local-machine)
4. Try if `.githooks/pre-commit` or `sh .githooks/pre-commit` runs inside your cloned _edamontology_ repo
5. Make a dummy change in `EDAM_dev.owl` using a text editor (best if you create an experimental Git branch for that), and try to commit it
6. Now replace all `owl:Class` in the `EDAM_dev.owl` file with for example `wol:Class` 🦉, and try to commit that change. It should fail now (returning 0), not allowing you to commit.
7. If it doesn't work properly, please describe your problem as a comment to this issue

[a good small task for newcomers, e.g. Outreachy applicants]

----

**Not sure how to start?**
 - Quick introduction|refresh of [Git and GitHub](https://coderefinery.github.io/git-refresher/02-refresher/) (101)
 - Install Git: see [here](https://coderefinery.github.io/git-refresher/01-setup) and [here](https://carpentries.github.io/workshop-template/#git)
 - Install a convenient [text editor](https://coderefinery.github.io/installation/editors/) ([see also](https://carpentries.github.io/workshop-template/#editor))
 - [Learn Git](https://coderefinery.github.io/git-intro/) (great for both beginners and advanced)
 - [Forking](https://coderefinery.github.io/git-collaborative/03-distributed/) a GitHub repository
 - Git hooks: [quick overview](https://coderefinery.github.io/git-collaborative/05-hooks/)

----

When this works, you're ready to edit EDAM locally! 👍🏽

(_Note 1_: There are also options to edit EDAM online, _e.g._ in Gitpod; and "Git-free" options to contribute with suggestions and comments in the [NCBO BioPortal](https://bioportal.bioontology.org/ontologies/EDAM?p=classes), [WebProtégé](https://webprotege.stanford.edu/#projects/4befad5f-f27b-430c-a07d-fcf635093169/edit/Classes), or suggest new concepts using an [issue template](https://github.com/edamontology/edamontology/issues/new/choose). EDAM-bioimaging can also be editted directly in WebProtégé or on GitHub, [details here](https://github.com/edamontology/edam-bioimaging#contributing).)

(_Note 2_: For someone who wants to script in Bash, or learn to, there is a very welcome possibility to improve the _pre-commit_ script for better user experience.)

### PR DESCRIPTION
**Pull request by Uttam-Singhh**
## Fixes #616 Set up an "offline" Git repository.

Created a new branch and replaced owl:Class with wol:Class.

### CODE REVIEW

**Review by matuskalas — COMMENTED** [review]
Indeed, all `owl:Class` changed to `wol:Class` 🦉👍🏽

**Comment by matuskalas** [comment]
Apologies again for the major delay in replying 🙇🏽‍♂️ and thanks for creating the pull request to document what happened! 👍🏽

For some reason the _pre-commit hook_ did not work for you, otherwise it would not allow you to commit b7af815.

Could you please try the following, and let us know what happens then?
- (#616 4.) Run `.githooks/pre-commit` or `sh .githooks/pre-commit` inside your cloned repo. It should output the location, version of git, and how many times `owl:Class` has been found in the `EDAM_dev.owl` file. In my case, it looks like this:
```
$ .githooks/pre-commit
INFO: Pre-commit hook running from /c/Users/Matus/Work/edamOntology/edamontology
git version 2.29.2.windows.2
0
```
It returns 0 because in this experiment I replaced all owls with wols 🦉
- Set up the location of _git hooks_ for this repo by `git config core.hooksPath .githooks` (Note: the version of git should be 2.9 or higher for this to work.)
- Now make a change in `EDAM_dev.owl` and try to commit. The commit should fail if there is zero-times `owl:Class` and succeed otherwise.

Please let us know how it worked for you, million thanks! 🙏🏽

**Comment by Uttam-Singhh** [comment]
Thank you so much @matuskalas !

When I tried to run `.githooks/pre-commit` It shows:

`INFO: Pre-commit hook running from /e/workspace/edamontology
git version 2.27.0.windows.1
0`

so should I update my git version?
Also, I don't think so git version should be affecting this.

**Comment by matuskalas** [comment]
The setup worked great, closing this PR now. Many thanks again for documenting it @Uttam-Singhh🙏🏽

**Comment by Uttam-Singhh** [comment]
Thank you @matuskalas!

**Pull request closed without merging**
