### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by Lukong123**

### CODE REVIEW

**Comment by Lukong123** [comment]
added commit message template

**Comment by Lukong123** [comment]
Edited wikipedia links

**Comment by LucieLamothe** [comment]
Good suggestions for git message

**Review by rioualen — APPROVED** [review]

**Comment by rioualen** [comment]
The wikipedia links have been corrected outside of this PR. 
If relevant, I suggest opening a new PR specifically for the git message suggestion, with a specific title.

**Pull request closed without merging**
