### PR TITLE
Workflows edam validation

### PR DESCRIPTION
**Pull request by LucieLamothe**
Addition of 4 workflows: 
Robot reasoner (ELK)
Robot report (selected robot tests)
Edamci (custom tool)
One workflow call the other 3 

the old ci_test.yml calling hermit and edamxpathvalidator is removed

### CODE REVIEW

**Comment by LucieLamothe** [comment]
Here I deleted ci_test.yml that runs edamxpathvalidator and hermit. Do we want it gone or shall I leave is and just removed the triggers?

**Comment by matuskalas** [comment]
> Here I deleted ci_test.yml that runs edamxpathvalidator and hermit. The issue is that some of the tests are still in curation in edamci meaning they would not be tested, maybe we should keep the "old" tests until more tests are running in edamci. @matuskalas @hmenager @albangaignard

Yes exactly, we should keep the old tests for now 👍🏽

**Comment by LucieLamothe** [comment]
image
____
image
____
image

____

**Review by matuskalas — APPROVED** [review]
Looks great! 🙌🏽
I'm very excited to see what happens after we merge it 😺

The plan is that @LucieLamothe squashes it and writes a commit msg...

**Pull request merged**
