### PR TITLE
Test conversion on dev version of the ontology

### PR DESCRIPTION
**Pull request by bryan-brancotte**
In order to highligh errors in the ontology, and/or edam2json

Need #705 to be solved to have error-less CI

### CODE REVIEW

**Comment by matuskalas** [comment]
Thanks a lot @bryan-brancotte, this is a great idea! 👍🏽

What will be the best way to test it with the fixed #705? (Merging `main` into this branch?)

**Comment by bryan-brancotte** [comment]
It is far from a real CI that check the validity of the owl, but it is a start

**Comment by bryan-brancotte** [comment]
> Thanks a lot @bryan-brancotte, this is a great idea! 👍🏽
> 
> What will be the best way to test it with the fixed #705? (Merging `main` into this branch?)

Yes, merging main into the branch

**Comment by bryan-brancotte** [comment]
Once main merge into that branch, the CI went well :)

**Review by matuskalas — APPROVED** [review]
Nice! Let's squash & merge it 🎃

**Pull request merged**
