### PR TITLE
Add terms (December 2021)

### LINKED ISSUE #757: New operation "Power test"
*Instructions:* When making a request, replace the text < between chevrons > after first reading the instructions.  The instructions can be removed. Do not change any other text, and please try to complete as much information as you can (your request will get acted on sooner if you do).

**Operation name:**  < Power test>

*Instructions:*  Name of operation, *e.g.* "Sequence aignment".  This is the most commonly used term.  

**Short description:** <Estimation of the statistical power of an experimental study>

*Instructions:* Short description, *e.g.* "Align (identify equivalent sites within) molecular sequences." A sentence or two describing the operation, specifically stating *what* is done but not *how*. Keep it concise, lucid and avoid jargon and acronyms. See http://edamontology.org/operation_0004 for examples.

**Parent URI(s):** < http://edamontology.org/operation_2238>

*Instructions:* URI(s) of suggested EDAM Operation parent(s) delimited by pipe ('|') *e.g.* "http://edamontology.org/operation_2928".  Pick the single, most relevant operation. In some (exceptional) cases, a broad operation type (top-level operation) *e.g.* "Comparison", "Calculation" *etc.* (see http://edamontology.org/operation_0004) may also be specified.

**Has Input:** <http://edamontology.org/data_2042>

**Has Output:** <http://edamontology.org/data_0951>

**Has Topic:** < http://edamontology.org/topic_3572|http://edamontology.org/topic_3365|http://edamontology.org/topic_3365>

**exactSynonym(s):** < Estimation of statistical power|Power analysis>

*Instructions:* Exact synonym(s) delimited by pipe ('|') *e.g.* "Sequence alignment generation". Other commonly-used terms, acronyms *etc.* by which the concept is referred to.  

**Wikipedia:** <https://en.wikipedia.org/wiki/Power_of_a_test>

*Instructions:* URL(s) to Wikipedia pages delimited by pipe ('|') *e.g.* "https://en.wikipedia.org/wiki/Sequence_alignment". Provide link(s) to relevant Wikipedia pages, if any.

**Comment:** < comment >

*Instructions:* Comment to the EDAM developers. Add any comments you like for the EDAM developers to consider.

### LINKED ISSUE #759: New Operation "DNA modification prediction"
**Operation name:**  < DNA modification prediction >

**Short description:** < The prediction of DNA modifications >

**Parent URI(s):** < http://edamontology.org/operation_0415 >

**Has Input:** < http://edamontology.org/data_3494 >

**Has Output:** < http://edamontology.org/data_1772 | http://edamontology.org/data_1276 >

**Has Topic:** < http://edamontology.org/topic_3295 | http://edamontology.org/topic_0160>

**exactSynonym(s):** < >

**Wikipedia:** < >

**Comment:** < >

### LINKED ISSUE #760: New operation "Disease transmission analysis"
**Operation name:**  < Disease transmission analysis >

**Short description:** < The analysis of the transmission of disease in a population >

**Parent URI(s):** <http://edamontology.org/operation_2945 >

**Has Input:** < >

**Has Output:** < http://edamontology.org/data_2048 >

**Has Topic:** <http://edamontology.org/topic_3324 | http://edamontology.org/topic_3305 >

**exactSynonym(s):** < >

**Wikipedia:** < >

**Comment:** < >

### LINKED ISSUE #761: Add narrow synonyms to "Statistical calculation" (http://edamontology.org/operation_2238)
The following terms could be added as narrow synonym to operation "Statistical calculation" (http://edamontology.org/operation_2238):
- False discovery rate estimation
- FDR estimation
- Multiple testing

### LINKED ISSUE #762: New operation "Multiple testing correction"
**Operation name:**  < Multiple testing correction>

**Short description:** < The correction of p-values from multiple statistical tests to correct for false positives. >

**Parent URI(s):** <http://edamontology.org/operation_2238 >

**Has Input:** < http://edamontology.org/data_1669 >

**Has Output:** < http://edamontology.org/data_3932 >

**Has Topic:** < http://edamontology.org/topic_2269 >

**exactSynonym(s):** <False discovery rate estimation | FDR estimation >

**Wikipedia:** <https://en.wikipedia.org/wiki/Multiple_comparisons_problem >

**Comment:** < See #761 for discussion>

### PR DESCRIPTION
**Pull request by Kigaard**
Adds "Power Test" (Fix #757).
Adds operation "DNA modification prediction" (Fix #759).
Adds operation "Disease transmission analysis" (Fix #760).
Adds operation "Multiple testing correction" (Fix #762 & closes #761).
Add formats PQR and PDBQT (Confer #239)

### CODE REVIEW

**Review by LucieLamothe — APPROVED** [review]

**Review by LucieLamothe — CHANGES_REQUESTED** [review]
See comments in the code

**Comment by Kigaard** [comment]
Hi @LucieLamothe 😄 The definitions for PQR and PDBQT and has been changed.

**Comment by LucieLamothe** [comment]
It's perfect Mads thank you!! I'm merging right away :smile:

**Review by LucieLamothe — APPROVED** [review]

**Comment by matuskalas** [comment]
TODO:
- [ ] The whitespaces and newlines between the concepts need to be standardised
- [ ] Documentation links need to be added to the formats. Do you have them at hand @Kigaard @veitveit @krab1k? Million thanks! 🙏🏽

**Pull request merged**
