### PR TITLE
Added: New format concept for PETab

### PR DESCRIPTION
**Pull request by AnkitaxPriya**
# This PR fixes issue #611 

# Summary 
I have modified the `EDAM_dev.owl` file of edamontology repository. 
I have added the format concept of "PETab" in the `EDAM_dev.owl` file, keeping in view all the instructions mentioned in the `CONTRIBUTING.md` file to add a new concept. 

@matuskalas kindly review my PR and let me know if any improvements are needed. 
Thank you.

### CODE REVIEW

**Review by matuskalas — CHANGES_REQUESTED** [review]
Super awesome, thank you so much @AnkitaxPriya for the quick and very nice implementation! 🙌🏽

Just 2 tiny things:
- The correct spelling is **PEtab** with a small **'t'**, would you please fix it?
- And the `<!--...` line seems to begin with one space too many.

E^6 thanks! 🙏🏽

**Comment by AnkitaxPriya** [comment]
@matuskalas I've made the necessary changes, kindly review my PR.

**Review by matuskalas — APPROVED** [review]
Awesome, thanks! 😊

**Comment by AnkitaxPriya** [comment]
Thanks a tonne for the guidance @matuskalas! 🙏

**Pull request merged**
