### PR TITLE
Modified isdebtag boolean datatype

### PR DESCRIPTION
**Pull request by LucieLamothe**

### CODE REVIEW

**Comment by matuskalas** [comment]
@hmenager @LucieLamothe @albangaignard could we please get CI checks in place so that this kind of invalid RDF is not accepted?

And in addition, we don't want any `rdf:datatype` annotations in the OWL file, because they just inflate it and are useless. Could we please add checks about that too?

**Comment by matuskalas** [comment]
Invalid, unmerged.

**Comment by matuskalas** [comment]
> @hmenager @LucieLamothe @albangaignard could we please get CI checks in place so that this kind of invalid RDF is not accepted?

Or is `rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true` just a valid RDF/XML literal? In that case, should we perhaps check for string `="` in literals?

**Comment by albangaignard** [comment]
Yes you can specify datatypes for RDF literals : https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal

**Comment by matuskalas** [comment]
@albangaignard says: We need to declare the datatype explicitly. No type inference on the Semantic Web.
@matuskalas says: Is it really possible in 2020s that a machine language cannot infer type from value?!

**Comment by matuskalas** [comment]
Anyhow, this is now fixed all over the OWL file (#798), even in the annotated targets in owl:Axioms⚒

**Pull request merged**
