### PR TITLE
spelling fixups

### PR DESCRIPTION
**Pull request by mr-c**
`codespell -I spelling-ignore.txt EDAM_dev.owl`

### CODE REVIEW

**Comment by matuskalas** [comment]
This is absolutely ultra-awesome, quadrillion thanks @mr-c 🙏🏽🙏🏽🙏🏽❤

I've been dreaming about a spellchecker tool like this, so that we can include it in the CI validation. Amazing, super cool, 💯🎆🎈🎇✨! 😊

**Comment by hmenager** [comment]
This is great! we'll check very soon with @LucieLamothe to add this to the CI!

**Review by LucieLamothe — APPROVED** [review]
I move the spelling-ignore.txt to the edamontology/caseologue repository since it will be run automaticly from there from now on. 
Made a few changes but it doesn't raise any spelling error, good to mere

**Comment by LucieLamothe** [comment]
Thank you so much @mr-c that is a great addition that we were looking forward to add and you helped us speed up the process! :+1:

**Pull request merged**
