### PR TITLE
Add N-Quads format

### PR DESCRIPTION
**Pull request by vemonet**
Similar to N-Triples but holding information about the statements graph. 

Definition taken from https://www.w3.org/TR/n-quads/

### CODE REVIEW

**Comment by joncison** [comment]
Apologies @vemonet for missing this last year.  A few things have changed since you made the request, so rather than manually resolve the conflicts I'll just add your changes directly (everything from your two commits).

Changes will appear in EDAM 1.24 (out in the next few days)

Thanks a million!

**Comment by bgruening** [comment]
Can this one be closed @joncison!

Thanks a lot @vemonet! Thats super cool! Keep them coming!

**Comment by joncison** [comment]
Now live in EDAM 1.24: http://edamontology.org/format_3956

Thanks again!

**Comment by vemonet** [comment]
Just noticed it has been integrated

I can now faithfully describe my N-Quad files using EDAM, thanks a lot!

**Pull request closed without merging**
