### PR TITLE
Fixing issue 644: Add post-commit hook

### PR DESCRIPTION
**Pull request by AnkitaxPriya**
# This PR fixes issue #644 

# Summary
I have added a simple bash script for `post-commit` in `.githooks` which displays a message after making a  commit for EDAM organization. 

Co-author: @matuskalas 

@matuskalas kindly review my script and let me know if any improvements are needed. Thank you.

### CODE REVIEW

**Comment by AnkitaxPriya** [comment]
@matuskalas and @hmenager why my checks are getting failed in every PR I make? Will this affect in merging my PR?

**Review by matuskalas — CHANGES_REQUESTED** [review]
Dear @AnkitaxPriya, I'm soooo sorry for keeping you waiting so long 😟

✅ The `post-commit` is excellent, thank you so much! 👍🏽 🥇 

And you have done a lot of highly appreciated work with the templates, too 🙏🏽 The templates have had to be discussed and tested quite a lot, therefore big sorry for keeping it still open.

➡ I would merge your `post-commit` immediately, but could you please redo it again in a new branch, branched out from the `main` branch? Million thanks!!!

So sorry again for complicating it for you, the templates still need to wait a bit (and they have their own pull requests, which is perfect!). But most importantly: **giant thanks for your idea of including the templates 🙌🏽 we really appreciate it, and the credit definitely goes to you!** 🙇🏽‍♂️

**Comment by AnkitaxPriya** [comment]
Sure @matuskalas I will do that. 
I am just facing an issue here. Whenever I make a new PR, all my previous commits come in that PR too. What must I do to fix that? 
Kindly guide me.

**Comment by Uttam-Singhh** [comment]
Hi @AnkitaxPriya 
You are facing this issue because you did all your work on the main branch itself, and now when you are trying to create a new branch and trying to create a new PR, the changes will still appear.

**Solution**
The solution to this problem is to create a new branch that is even with the main edamontology branch.
Go to your command line or git bash and create a new branch using this command -
`git checkout -b 'branch_name' upstream/master`

If you have set up your upstream this should work, If not please add upstream first.(Let me know if you need help)

Now your new branch is ready that is even with the main edamontology branch.
Now if you can add your changes in this branch and can create a new PR. 😊

**Comment by matuskalas** [comment]
Thanks for answering @Uttam-Singhh!

Just some additional clarification:
- @AnkitaxPriya's `main` branch is "clean", forked from the central repo
- The commits were done in separate branches, but the new branch (such as this `issue-644`) was created from the previous feature branch instead of the `main` branch
- The default branch in this central repo is called `main` ("master" has been renamed and doesn't exist anymore)

**Comment by AnkitaxPriya** [comment]
Thank you for the help @matuskalas and @Uttam-Singhh. I successfully made the required changes.

**Comment by LucieLamothe** [comment]
.githooks/ post-commit can be added

**Comment by matuskalas** [comment]
This has been merged in #658

**Pull request closed without merging**
