### PR TITLE
Added concept for Electrocardiography

### PR DESCRIPTION
**Pull request by drashti171299**
I have added a new concept which contains the information for Electrocardiography. The content was provided by @Kigaard

### CODE REVIEW

**Review by matuskalas — CHANGES_REQUESTED** [review]
Thank you very much @drashti171299, this is excellent and very helpful! 🙇🏽‍♂️ 

Just one little thing: Would you please remove the line with the `comment`? We don't need it in EDAM. It was an important comment with respect to why to add this, but shouldn't be recorded inside of the ontology. Many thanks!🙏🏽

**Comment by drashti171299** [comment]
Okay I will remove it @matuskalas

**Comment by drashti171299** [comment]
@matuskalas first let this PR approved and then I will take merged code then complete other issues. 👍

**Comment by matuskalas** [comment]
Perfect, thank you!🙆  Would you please once again update the numerical ID, there was another addition to the upstream main in the meantime 😄 Million thanks!!!

**Comment by drashti171299** [comment]
@matuskalas how many new concepts are added?? I mean I should increment next I'd by 1 or 2?

**Review by matuskalas — APPROVED** [review]
Awesome, thank you so much👍🏽

**Comment by drashti171299** [comment]
Thanks for the corrections @matuskalas

**Comment by drashti171299** [comment]
image
can you merge this pull request ?

**Comment by matuskalas** [comment]
@drashti171299 for curiousity: Is that what you pasted the only thing GitHub shows you about the merging? Or does it suggest any other options?

(I'll do the merging late tonight)

**Comment by drashti171299** [comment]
it is not allowing me to merge because of the conflict file "EDAM_dev.owl". but no worries. I will take the merged code by tonight. and then add other concepts. 😊👍

**Comment by matuskalas** [comment]
Merged in #692

**Pull request closed without merging**
