### PR TITLE
Update README.md to download the stable version

### PR DESCRIPTION
**Pull request by Uttam-Singhh**
#623 Now, the link to download the Stable Version is working.
@matuskalas Please check.

### CODE REVIEW

**Review by raashika03 — COMMENTED** [review]
downloadable should be there downloable isn't a meaningful word :smile:

**Comment by Uttam-Singhh** [comment]
Well, I didn't change that, it was already "downloable" in the main repo.
Thank you @raashika03 I will also improve that typo.

**Comment by matuskalas** [comment]
The link to download the latest stable _.owl_ in README.md looks like working just fine. Please give a notice again, with some details, if it still doesn't work for you @Uttam-Singhh. Million thanks🙇🏽‍♂️

**Comment by Uttam-Singhh** [comment]
Yes! It is working now!
Thanks!

**Pull request closed without merging**
